import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { ArrowRight, LockKeyhole, Link2, ShieldCheck, FileCheck2, Star, MessageCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Reveal } from "@/components/brand/Reveal";
import { AnnouncementBar, SiteFooter, SiteHeader } from "@/components/site/SiteChrome";
import { FindTime } from "@/components/site/FindTime";
import { SituationChecklist } from "@/components/site/SituationChecklist";
import { SERVICES } from "@/lib/services";
import { SERVICE_PHOTOS } from "@/components/site/service-photos";
import priya from "@/assets/priya-portrait.jpg";

const TITLE = "Patel Tax & Bookkeeping — Taxes, without the chase";
const DESC = "Book with Priya Patel, EA in Edison, NJ. Get a personal checklist, share your documents privately, and arrive ready.";
export const Route = createFileRoute("/")({ head: () => ({ meta: [
  { title: TITLE }, { name: "description", content: DESC }, { property: "og:title", content: TITLE }, { property: "og:description", content: DESC }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: Home });
function SectionHeading({ overline, children }: { overline: string; children: React.ReactNode }) { return <div><p className="text-xs font-bold uppercase text-ink">{overline}</p><h2 className="mt-3 font-serif text-4xl leading-tight text-deep-ink sm:text-5xl">{children}</h2></div>; }
function Home() { return <div className="min-h-screen overflow-x-clip"><AnnouncementBar/><SiteHeader/><main><Hero/><SituationChecklist/><Services/><Profile/><Reviews/><Privacy/><Faq/></main><SiteFooter/><MobileBookBar/></div>; }
function Hero() { return <section id="home" className="mx-auto max-w-6xl px-5 pb-16 pt-16 sm:pt-24"><Reveal><p className="text-xs font-semibold uppercase text-ink">Tax preparation in Edison, New Jersey</p><h1 className="mt-5 max-w-[800px] font-serif text-[42px] leading-[1.06] text-deep-ink sm:text-[72px] sm:leading-[1.03]">Taxes, without <em className="text-ink">the chase.</em></h1><p className="mt-5 max-w-xl text-base leading-relaxed text-muted-foreground sm:text-lg">Book in two minutes. We’ll tell you exactly what to bring, and check it before you arrive.</p><div className="mt-10 max-w-5xl"><FindTime/></div><p className="mt-5 text-sm text-muted-foreground">Confirmed instantly · No payment now · <Link to="/book/returning" className="font-semibold text-ink underline underline-offset-4">Returning client?</Link></p></Reveal></section>; }
function Services() { return <section id="services" className="mx-auto max-w-6xl scroll-mt-24 px-5 py-20"><SectionHeading overline="Services">The right help for your return.</SectionHeading><p className="mt-3 text-muted-foreground">Straightforward pricing. You pay when your return is filed, not when you book.</p><div className="mt-10 grid gap-7 sm:grid-cols-2 lg:grid-cols-3">{SERVICES.map((s,i)=><Reveal key={s.id} delay={(i%3)*0.07}><Link to="/services/$slug" params={{slug:s.id}} className="group block h-full"><img src={SERVICE_PHOTOS[s.id]} alt="" loading="lazy" width={900} height={650} className="aspect-[1.55] w-full rounded-[14px] object-cover"/><div className="pt-5"><h3 className="font-serif text-[26px] leading-tight text-deep-ink">{s.name}</h3><p className="mt-2 text-sm text-muted-foreground">{s.blurb}</p><p className="tabular mt-4 text-sm font-semibold text-ink">{s.minutes} min · {s.from ? "from " : ""}${s.price} <ArrowRight className="ml-2 inline size-4 transition-transform group-hover:translate-x-1"/></p><p className="mt-3 inline-flex items-center gap-1 text-xs text-muted-foreground"><Star className="size-3 fill-current text-warning"/> 4.9 <span>· illustrative rating</span></p></div></Link></Reveal>)}</div></section>; }
function Profile() { return <section id="about" className="scroll-mt-24 bg-sheet py-20"><div className="mx-auto grid max-w-6xl gap-10 px-5 md:grid-cols-[minmax(0,0.82fr)_minmax(0,1fr)] md:items-center md:gap-20"><Reveal><img src={priya} alt="Illustrative portrait representing Priya Patel; not an actual photograph of Priya" loading="lazy" width={850} height={1050} className="aspect-[4/4.5] w-full rounded-[14px] object-cover object-top"/></Reveal><Reveal delay={0.1}><p className="text-xs font-semibold uppercase text-ink">Meet Priya</p><h2 className="mt-3 font-serif text-4xl text-deep-ink sm:text-5xl">Real attention, from start to finish.</h2><p className="mt-3 text-sm font-semibold text-ink">Priya Patel · IRS Enrolled Agent</p><div className="mt-8 grid grid-cols-3 gap-3 border-y border-border py-6"><div><strong className="tabular block font-serif text-3xl">12</strong><span className="text-xs text-muted-foreground">years in Edison</span></div><div><strong className="tabular block font-serif text-3xl">1,800+</strong><span className="text-xs text-muted-foreground">returns</span></div><div><strong className="tabular block font-serif text-3xl">4.9</strong><span className="text-xs text-muted-foreground">rating</span></div></div><p className="mt-7 leading-relaxed text-muted-foreground">Priya helps local families, freelancers and landlords make sense of their taxes. Her practice is small by choice: when you book, you work directly with her, from your first document to the final signature.</p><Button asChild variant="outline" className="mt-7"><Link to="/book">Ask a question <MessageCircle/></Link></Button><p className="mt-3 text-xs text-muted-foreground">Portrait is illustrative; replace with Priya’s real photo before launch.</p></Reveal></div></section>; }
const REVIEWS = [
  { name: "Anita R.", town: "Edison", quote: "I uploaded everything the week before. For once I didn't have to come back with another document." },
  { name: "Marcus L.", town: "Metuchen", quote: "Priya explained my freelance income clearly. I finally understood what I was filing." },
  { name: "Deepa S.", town: "Iselin", quote: "The rental checklist was spot on. I knew exactly what to gather before our appointment." },
  { name: "Rohan M.", town: "Edison", quote: "Booking took minutes, and I could see what was still missing without another phone call." },
  { name: "Elena P.", town: "Woodbridge", quote: "Calm, careful, and never rushed. It felt like she knew my situation before we even sat down." },
  { name: "Samir K.", town: "Piscataway", quote: "The reminders made it easy to get everything in on time. A genuinely easier tax season." },
];
function Reviews() { return <section id="reviews" className="mx-auto max-w-6xl scroll-mt-24 px-5 py-20"><SectionHeading overline="Client experiences">Good words from the neighborhood.</SectionHeading><div className="mt-10 grid gap-10 lg:grid-cols-[250px_1fr]"><div><p className="tabular font-serif text-7xl leading-none text-deep-ink">4.9</p><p className="mt-2 flex gap-1 text-warning" aria-label="Rated 4.9 out of 5">{Array.from({length:5},(_,i)=><Star key={i} className="size-4 fill-current"/>)}</p><p className="mt-2 text-xs text-muted-foreground">Illustrative rating and reviews; verify before publishing.</p><div className="mt-7 space-y-3">{[["Clarity",98],["Speed",96],["Communication",99],["Value",94]].map(([label,value])=><div key={label}><div className="mb-1 flex justify-between text-xs text-muted-foreground"><span>{label}</span><span className="tabular">{value}%</span></div><div className="h-1.5 rounded-full bg-sheet"><div className="h-full rounded-full bg-ink" style={{width:`${value}%`}}/></div></div>)}</div></div><div className="grid gap-5 sm:grid-cols-2"><div className="contents">{REVIEWS.map(r=><figure key={r.name} className="rounded-[14px] border border-border p-6 shadow-sheet"><div className="mb-4 flex gap-0.5 text-warning" aria-label="Five stars">{Array.from({length:5},(_,i)=><Star key={i} className="size-3 fill-current"/>)}</div><blockquote className="text-sm leading-relaxed text-deep-ink">“{r.quote}”</blockquote><figcaption className="mt-5 text-xs font-semibold text-ink">{r.name} <span className="font-normal text-muted-foreground">· {r.town}</span></figcaption></figure>)}</div></div></div></section>; }
function Privacy() { const points=[{icon:LockKeyhole,title:"Private storage",text:"Your files aren't public. Only Priya can see them."},{icon:Link2,title:"Links that expire",text:"Document viewing links stop working after a short time."},{icon:ShieldCheck,title:"No sensitive number online",text:"We never ask for your Social Security number."},{icon:FileCheck2,title:"Only what you need",text:"A personal list shows exactly what to share, after you book."}]; return <section className="bg-sheet py-20"><div className="mx-auto max-w-6xl px-5"><SectionHeading overline="Your documents are safe">Your paperwork stays yours.</SectionHeading><div className="mt-10 grid gap-x-16 gap-y-10 sm:grid-cols-2">{points.map(p=><div key={p.title} className="flex gap-4"><p.icon className="mt-1 size-6 shrink-0 text-ink" strokeWidth={1.7}/><div><h3 className="font-serif text-2xl text-deep-ink">{p.title}</h3><p className="mt-1 text-sm leading-relaxed text-muted-foreground">{p.text}</p></div></div>)}</div></div></section>; }
function Faq() { const qs: [string, string][] = [
  ["What should I bring?", "After booking, you'll get a checklist made for your situation. Upload what you have before you arrive; documents never hold up booking."],
  ["Video call or in person?", "Both work the same way. Select what works for you when booking, then upload your documents privately beforehand."],
  ["Can I reschedule?", "Yes. Use the link in your confirmation message to choose another available time."],
  ["Can you file an extension?", "Yes. An extension can give you until October 15 to file, though any taxes owed are still due in April."],
  ["What are the key deadlines?", "Most individual returns are due April 15; extended returns are generally due October 15. Your exact deadline can vary."],
]; return <section id="faq" className="mx-auto grid max-w-6xl gap-10 px-5 py-20 md:grid-cols-[0.8fr_1.2fr]"><SectionHeading overline="Questions">Good to know.</SectionHeading><Accordion type="single" collapsible className="border-t border-border">{qs.map(([q,a])=><AccordionItem key={q} value={q}><AccordionTrigger className="py-5 text-left font-serif text-xl font-normal text-deep-ink">{q}</AccordionTrigger><AccordionContent className="pb-5 text-sm leading-relaxed text-muted-foreground">{a}</AccordionContent></AccordionItem>)}</Accordion></section>; }
function MobileBookBar() { const [visible, setVisible] = useState(false); useEffect(() => { const onScroll = () => { const hero = document.getElementById("home"); if (hero) setVisible(hero.getBoundingClientRect().bottom <= 0); }; onScroll(); window.addEventListener("scroll", onScroll, { passive: true }); return () => window.removeEventListener("scroll", onScroll); }, []); return visible ? <div className="fixed inset-x-0 bottom-0 z-30 flex items-center justify-between border-t border-border bg-background px-5 py-3 shadow-lift md:hidden"><p className="text-xs text-muted-foreground">Appointments <span className="tabular block text-sm font-semibold text-deep-ink">From $150</span></p><Button asChild size="sm"><Link to="/book">Book <ArrowRight/></Link></Button></div> : null; }
