/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ATokenRouteImport } from './routes/a.$token'
import { Route as BookIndexRouteImport } from './routes/book.index'
import { Route as BookConfirmedRouteImport } from './routes/book.confirmed'
import { Route as BookReturningRouteImport } from './routes/book.returning'
import { Route as ClaimTokenRouteImport } from './routes/claim.$token'
import { Route as ManageTokenRouteImport } from './routes/manage.$token'
import { Route as MoveTokenRouteImport } from './routes/move.$token'
import { Route as ApiPublicCronAutomationsRouteImport } from './routes/api/public/cron/automations'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ATokenRoute = ATokenRouteImport.update({
  id: '/a/$token',
  path: '/a/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIndexRoute = BookIndexRouteImport.update({
  id: '/book/',
  path: '/book/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookConfirmedRoute = BookConfirmedRouteImport.update({
  id: '/book/confirmed',
  path: '/book/confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const BookReturningRoute = BookReturningRouteImport.update({
  id: '/book/returning',
  path: '/book/returning',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimTokenRoute = ClaimTokenRouteImport.update({
  id: '/claim/$token',
  path: '/claim/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageTokenRoute = ManageTokenRouteImport.update({
  id: '/manage/$token',
  path: '/manage/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const MoveTokenRoute = MoveTokenRouteImport.update({
  id: '/move/$token',
  path: '/move/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronAutomationsRoute =
  ApiPublicCronAutomationsRouteImport.update({
    id: '/api/public/cron/automations',
    path: '/api/public/cron/automations',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a/$token': typeof ATokenRoute
  '/book/confirmed': typeof BookConfirmedRoute
  '/book/returning': typeof BookReturningRoute
  '/claim/$token': typeof ClaimTokenRoute
  '/manage/$token': typeof ManageTokenRoute
  '/move/$token': typeof MoveTokenRoute
  '/book/': typeof BookIndexRoute
  '/api/public/cron/automations': typeof ApiPublicCronAutomationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a/$token': typeof ATokenRoute
  '/book/confirmed': typeof BookConfirmedRoute
  '/book/returning': typeof BookReturningRoute
  '/claim/$token': typeof ClaimTokenRoute
  '/manage/$token': typeof ManageTokenRoute
  '/move/$token': typeof MoveTokenRoute
  '/book': typeof BookIndexRoute
  '/api/public/cron/automations': typeof ApiPublicCronAutomationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a/$token': typeof ATokenRoute
  '/book/confirmed': typeof BookConfirmedRoute
  '/book/returning': typeof BookReturningRoute
  '/claim/$token': typeof ClaimTokenRoute
  '/manage/$token': typeof ManageTokenRoute
  '/move/$token': typeof MoveTokenRoute
  '/book/': typeof BookIndexRoute
  '/api/public/cron/automations': typeof ApiPublicCronAutomationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a/$token'
    | '/book/confirmed'
    | '/book/returning'
    | '/claim/$token'
    | '/manage/$token'
    | '/move/$token'
    | '/book/'
    | '/api/public/cron/automations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a/$token'
    | '/book/confirmed'
    | '/book/returning'
    | '/claim/$token'
    | '/manage/$token'
    | '/move/$token'
    | '/book'
    | '/api/public/cron/automations'
  id:
    | '__root__'
    | '/'
    | '/a/$token'
    | '/book/confirmed'
    | '/book/returning'
    | '/claim/$token'
    | '/manage/$token'
    | '/move/$token'
    | '/book/'
    | '/api/public/cron/automations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ATokenRoute: typeof ATokenRoute
  BookConfirmedRoute: typeof BookConfirmedRoute
  BookReturningRoute: typeof BookReturningRoute
  ClaimTokenRoute: typeof ClaimTokenRoute
  ManageTokenRoute: typeof ManageTokenRoute
  MoveTokenRoute: typeof MoveTokenRoute
  BookIndexRoute: typeof BookIndexRoute
  ApiPublicCronAutomationsRoute: typeof ApiPublicCronAutomationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a/$token': {
      id: '/a/$token'
      path: '/a/$token'
      fullPath: '/a/$token'
      preLoaderRoute: typeof ATokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/': {
      id: '/book/'
      path: '/book'
      fullPath: '/book/'
      preLoaderRoute: typeof BookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/confirmed': {
      id: '/book/confirmed'
      path: '/book/confirmed'
      fullPath: '/book/confirmed'
      preLoaderRoute: typeof BookConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/returning': {
      id: '/book/returning'
      path: '/book/returning'
      fullPath: '/book/returning'
      preLoaderRoute: typeof BookReturningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim/$token': {
      id: '/claim/$token'
      path: '/claim/$token'
      fullPath: '/claim/$token'
      preLoaderRoute: typeof ClaimTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/$token': {
      id: '/manage/$token'
      path: '/manage/$token'
      fullPath: '/manage/$token'
      preLoaderRoute: typeof ManageTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/move/$token': {
      id: '/move/$token'
      path: '/move/$token'
      fullPath: '/move/$token'
      preLoaderRoute: typeof MoveTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/automations': {
      id: '/api/public/cron/automations'
      path: '/api/public/cron/automations'
      fullPath: '/api/public/cron/automations'
      preLoaderRoute: typeof ApiPublicCronAutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ATokenRoute: ATokenRoute,
  BookConfirmedRoute: BookConfirmedRoute,
  BookReturningRoute: BookReturningRoute,
  ClaimTokenRoute: ClaimTokenRoute,
  ManageTokenRoute: ManageTokenRoute,
  MoveTokenRoute: MoveTokenRoute,
  BookIndexRoute: BookIndexRoute,
  ApiPublicCronAutomationsRoute: ApiPublicCronAutomationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
