/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedOwnerRouteImport } from './routes/_authenticated/owner'
import { Route as ATokenRouteImport } from './routes/a.$token'
import { Route as BookIndexRouteImport } from './routes/book.index'
import { Route as BookConfirmedRouteImport } from './routes/book.confirmed'
import { Route as BookReturningRouteImport } from './routes/book.returning'
import { Route as ClaimTokenRouteImport } from './routes/claim.$token'
import { Route as ManageTokenRouteImport } from './routes/manage.$token'
import { Route as MoveTokenRouteImport } from './routes/move.$token'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as AuthenticatedOwnerIndexRouteImport } from './routes/_authenticated/owner.index'
import { Route as AuthenticatedOwnerCalendarRouteImport } from './routes/_authenticated/owner.calendar'
import { Route as AuthenticatedOwnerInsightsRouteImport } from './routes/_authenticated/owner.insights'
import { Route as AuthenticatedOwnerNeedsRouteImport } from './routes/_authenticated/owner.needs'
import { Route as AuthenticatedOwnerOutboxRouteImport } from './routes/_authenticated/owner.outbox'
import { Route as AuthenticatedOwnerSettingsRouteImport } from './routes/_authenticated/owner.settings'
import { Route as AuthenticatedOwnerClientsIndexRouteImport } from './routes/_authenticated/owner.clients.index'
import { Route as AuthenticatedOwnerClientsIdRouteImport } from './routes/_authenticated/owner.clients.$id'
import { Route as ApiPublicCronAutomationsRouteImport } from './routes/api/public/cron/automations'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOwnerRoute = AuthenticatedOwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ATokenRoute = ATokenRouteImport.update({
  id: '/a/$token',
  path: '/a/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIndexRoute = BookIndexRouteImport.update({
  id: '/book/',
  path: '/book/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookConfirmedRoute = BookConfirmedRouteImport.update({
  id: '/book/confirmed',
  path: '/book/confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const BookReturningRoute = BookReturningRouteImport.update({
  id: '/book/returning',
  path: '/book/returning',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimTokenRoute = ClaimTokenRouteImport.update({
  id: '/claim/$token',
  path: '/claim/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageTokenRoute = ManageTokenRouteImport.update({
  id: '/manage/$token',
  path: '/manage/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const MoveTokenRoute = MoveTokenRouteImport.update({
  id: '/move/$token',
  path: '/move/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOwnerIndexRoute = AuthenticatedOwnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedOwnerRoute,
} as any)
const AuthenticatedOwnerCalendarRoute =
  AuthenticatedOwnerCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedOwnerRoute,
  } as any)
const AuthenticatedOwnerInsightsRoute =
  AuthenticatedOwnerInsightsRouteImport.update({
    id: '/insights',
    path: '/insights',
    getParentRoute: () => AuthenticatedOwnerRoute,
  } as any)
const AuthenticatedOwnerNeedsRoute = AuthenticatedOwnerNeedsRouteImport.update({
  id: '/needs',
  path: '/needs',
  getParentRoute: () => AuthenticatedOwnerRoute,
} as any)
const AuthenticatedOwnerOutboxRoute =
  AuthenticatedOwnerOutboxRouteImport.update({
    id: '/outbox',
    path: '/outbox',
    getParentRoute: () => AuthenticatedOwnerRoute,
  } as any)
const AuthenticatedOwnerSettingsRoute =
  AuthenticatedOwnerSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedOwnerRoute,
  } as any)
const AuthenticatedOwnerClientsIndexRoute =
  AuthenticatedOwnerClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedOwnerRoute,
  } as any)
const AuthenticatedOwnerClientsIdRoute =
  AuthenticatedOwnerClientsIdRouteImport.update({
    id: '/clients/$id',
    path: '/clients/$id',
    getParentRoute: () => AuthenticatedOwnerRoute,
  } as any)
const ApiPublicCronAutomationsRoute =
  ApiPublicCronAutomationsRouteImport.update({
    id: '/api/public/cron/automations',
    path: '/api/public/cron/automations',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/owner': typeof AuthenticatedOwnerRouteWithChildren
  '/a/$token': typeof ATokenRoute
  '/book/confirmed': typeof BookConfirmedRoute
  '/book/returning': typeof BookReturningRoute
  '/claim/$token': typeof ClaimTokenRoute
  '/manage/$token': typeof ManageTokenRoute
  '/move/$token': typeof MoveTokenRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/book/': typeof BookIndexRoute
  '/owner/calendar': typeof AuthenticatedOwnerCalendarRoute
  '/owner/insights': typeof AuthenticatedOwnerInsightsRoute
  '/owner/needs': typeof AuthenticatedOwnerNeedsRoute
  '/owner/outbox': typeof AuthenticatedOwnerOutboxRoute
  '/owner/settings': typeof AuthenticatedOwnerSettingsRoute
  '/owner/': typeof AuthenticatedOwnerIndexRoute
  '/owner/clients/$id': typeof AuthenticatedOwnerClientsIdRoute
  '/api/public/cron/automations': typeof ApiPublicCronAutomationsRoute
  '/owner/clients/': typeof AuthenticatedOwnerClientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/a/$token': typeof ATokenRoute
  '/book/confirmed': typeof BookConfirmedRoute
  '/book/returning': typeof BookReturningRoute
  '/claim/$token': typeof ClaimTokenRoute
  '/manage/$token': typeof ManageTokenRoute
  '/move/$token': typeof MoveTokenRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/book': typeof BookIndexRoute
  '/owner/calendar': typeof AuthenticatedOwnerCalendarRoute
  '/owner/insights': typeof AuthenticatedOwnerInsightsRoute
  '/owner/needs': typeof AuthenticatedOwnerNeedsRoute
  '/owner/outbox': typeof AuthenticatedOwnerOutboxRoute
  '/owner/settings': typeof AuthenticatedOwnerSettingsRoute
  '/owner': typeof AuthenticatedOwnerIndexRoute
  '/owner/clients/$id': typeof AuthenticatedOwnerClientsIdRoute
  '/api/public/cron/automations': typeof ApiPublicCronAutomationsRoute
  '/owner/clients': typeof AuthenticatedOwnerClientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/owner': typeof AuthenticatedOwnerRouteWithChildren
  '/a/$token': typeof ATokenRoute
  '/book/confirmed': typeof BookConfirmedRoute
  '/book/returning': typeof BookReturningRoute
  '/claim/$token': typeof ClaimTokenRoute
  '/manage/$token': typeof ManageTokenRoute
  '/move/$token': typeof MoveTokenRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/book/': typeof BookIndexRoute
  '/_authenticated/owner/calendar': typeof AuthenticatedOwnerCalendarRoute
  '/_authenticated/owner/insights': typeof AuthenticatedOwnerInsightsRoute
  '/_authenticated/owner/needs': typeof AuthenticatedOwnerNeedsRoute
  '/_authenticated/owner/outbox': typeof AuthenticatedOwnerOutboxRoute
  '/_authenticated/owner/settings': typeof AuthenticatedOwnerSettingsRoute
  '/_authenticated/owner/': typeof AuthenticatedOwnerIndexRoute
  '/_authenticated/owner/clients/$id': typeof AuthenticatedOwnerClientsIdRoute
  '/api/public/cron/automations': typeof ApiPublicCronAutomationsRoute
  '/_authenticated/owner/clients/': typeof AuthenticatedOwnerClientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/owner'
    | '/a/$token'
    | '/book/confirmed'
    | '/book/returning'
    | '/claim/$token'
    | '/manage/$token'
    | '/move/$token'
    | '/services/$slug'
    | '/book/'
    | '/owner/calendar'
    | '/owner/insights'
    | '/owner/needs'
    | '/owner/outbox'
    | '/owner/settings'
    | '/owner/'
    | '/owner/clients/$id'
    | '/api/public/cron/automations'
    | '/owner/clients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/a/$token'
    | '/book/confirmed'
    | '/book/returning'
    | '/claim/$token'
    | '/manage/$token'
    | '/move/$token'
    | '/services/$slug'
    | '/book'
    | '/owner/calendar'
    | '/owner/insights'
    | '/owner/needs'
    | '/owner/outbox'
    | '/owner/settings'
    | '/owner'
    | '/owner/clients/$id'
    | '/api/public/cron/automations'
    | '/owner/clients'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/owner'
    | '/a/$token'
    | '/book/confirmed'
    | '/book/returning'
    | '/claim/$token'
    | '/manage/$token'
    | '/move/$token'
    | '/services/$slug'
    | '/book/'
    | '/_authenticated/owner/calendar'
    | '/_authenticated/owner/insights'
    | '/_authenticated/owner/needs'
    | '/_authenticated/owner/outbox'
    | '/_authenticated/owner/settings'
    | '/_authenticated/owner/'
    | '/_authenticated/owner/clients/$id'
    | '/api/public/cron/automations'
    | '/_authenticated/owner/clients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ATokenRoute: typeof ATokenRoute
  BookConfirmedRoute: typeof BookConfirmedRoute
  BookReturningRoute: typeof BookReturningRoute
  ClaimTokenRoute: typeof ClaimTokenRoute
  ManageTokenRoute: typeof ManageTokenRoute
  MoveTokenRoute: typeof MoveTokenRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  BookIndexRoute: typeof BookIndexRoute
  ApiPublicCronAutomationsRoute: typeof ApiPublicCronAutomationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/owner': {
      id: '/_authenticated/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof AuthenticatedOwnerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/a/$token': {
      id: '/a/$token'
      path: '/a/$token'
      fullPath: '/a/$token'
      preLoaderRoute: typeof ATokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/': {
      id: '/book/'
      path: '/book'
      fullPath: '/book/'
      preLoaderRoute: typeof BookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/confirmed': {
      id: '/book/confirmed'
      path: '/book/confirmed'
      fullPath: '/book/confirmed'
      preLoaderRoute: typeof BookConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/returning': {
      id: '/book/returning'
      path: '/book/returning'
      fullPath: '/book/returning'
      preLoaderRoute: typeof BookReturningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim/$token': {
      id: '/claim/$token'
      path: '/claim/$token'
      fullPath: '/claim/$token'
      preLoaderRoute: typeof ClaimTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/$token': {
      id: '/manage/$token'
      path: '/manage/$token'
      fullPath: '/manage/$token'
      preLoaderRoute: typeof ManageTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/move/$token': {
      id: '/move/$token'
      path: '/move/$token'
      fullPath: '/move/$token'
      preLoaderRoute: typeof MoveTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/owner/': {
      id: '/_authenticated/owner/'
      path: '/'
      fullPath: '/owner/'
      preLoaderRoute: typeof AuthenticatedOwnerIndexRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/calendar': {
      id: '/_authenticated/owner/calendar'
      path: '/calendar'
      fullPath: '/owner/calendar'
      preLoaderRoute: typeof AuthenticatedOwnerCalendarRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/insights': {
      id: '/_authenticated/owner/insights'
      path: '/insights'
      fullPath: '/owner/insights'
      preLoaderRoute: typeof AuthenticatedOwnerInsightsRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/needs': {
      id: '/_authenticated/owner/needs'
      path: '/needs'
      fullPath: '/owner/needs'
      preLoaderRoute: typeof AuthenticatedOwnerNeedsRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/outbox': {
      id: '/_authenticated/owner/outbox'
      path: '/outbox'
      fullPath: '/owner/outbox'
      preLoaderRoute: typeof AuthenticatedOwnerOutboxRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/settings': {
      id: '/_authenticated/owner/settings'
      path: '/settings'
      fullPath: '/owner/settings'
      preLoaderRoute: typeof AuthenticatedOwnerSettingsRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/clients/': {
      id: '/_authenticated/owner/clients/'
      path: '/clients'
      fullPath: '/owner/clients/'
      preLoaderRoute: typeof AuthenticatedOwnerClientsIndexRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/clients/$id': {
      id: '/_authenticated/owner/clients/$id'
      path: '/clients/$id'
      fullPath: '/owner/clients/$id'
      preLoaderRoute: typeof AuthenticatedOwnerClientsIdRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/api/public/cron/automations': {
      id: '/api/public/cron/automations'
      path: '/api/public/cron/automations'
      fullPath: '/api/public/cron/automations'
      preLoaderRoute: typeof ApiPublicCronAutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedOwnerRouteChildren {
  AuthenticatedOwnerCalendarRoute: typeof AuthenticatedOwnerCalendarRoute
  AuthenticatedOwnerInsightsRoute: typeof AuthenticatedOwnerInsightsRoute
  AuthenticatedOwnerNeedsRoute: typeof AuthenticatedOwnerNeedsRoute
  AuthenticatedOwnerOutboxRoute: typeof AuthenticatedOwnerOutboxRoute
  AuthenticatedOwnerSettingsRoute: typeof AuthenticatedOwnerSettingsRoute
  AuthenticatedOwnerIndexRoute: typeof AuthenticatedOwnerIndexRoute
  AuthenticatedOwnerClientsIdRoute: typeof AuthenticatedOwnerClientsIdRoute
  AuthenticatedOwnerClientsIndexRoute: typeof AuthenticatedOwnerClientsIndexRoute
}

const AuthenticatedOwnerRouteChildren: AuthenticatedOwnerRouteChildren = {
  AuthenticatedOwnerCalendarRoute: AuthenticatedOwnerCalendarRoute,
  AuthenticatedOwnerInsightsRoute: AuthenticatedOwnerInsightsRoute,
  AuthenticatedOwnerNeedsRoute: AuthenticatedOwnerNeedsRoute,
  AuthenticatedOwnerOutboxRoute: AuthenticatedOwnerOutboxRoute,
  AuthenticatedOwnerSettingsRoute: AuthenticatedOwnerSettingsRoute,
  AuthenticatedOwnerIndexRoute: AuthenticatedOwnerIndexRoute,
  AuthenticatedOwnerClientsIdRoute: AuthenticatedOwnerClientsIdRoute,
  AuthenticatedOwnerClientsIndexRoute: AuthenticatedOwnerClientsIndexRoute,
}

const AuthenticatedOwnerRouteWithChildren =
  AuthenticatedOwnerRoute._addFileChildren(AuthenticatedOwnerRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOwnerRoute: typeof AuthenticatedOwnerRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOwnerRoute: AuthenticatedOwnerRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ATokenRoute: ATokenRoute,
  BookConfirmedRoute: BookConfirmedRoute,
  BookReturningRoute: BookReturningRoute,
  ClaimTokenRoute: ClaimTokenRoute,
  ManageTokenRoute: ManageTokenRoute,
  MoveTokenRoute: MoveTokenRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  BookIndexRoute: BookIndexRoute,
  ApiPublicCronAutomationsRoute: ApiPublicCronAutomationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
